# Generated by Django 6.1 on 2026-09-03 05:09

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[apps.common.validators.validate_image_file],
            ),
        ),
    ]
